services:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
  
  homeassistant:
    image: homeassistant/home-assistant:2024.12.1
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    depends_on: 
      - mosquitto

  nodered:
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "./nodered/data:/data"
    depends_on:
      - mosquitto

  cloudflared:
      image: cloudflare/cloudflared
      restart: unless-stopped
      command: tunnel run
      network_mode: host
      environment:
        - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      depends_on:
        - homeassistant 

